# Generated by Django 4.1.1 on 2022-10-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "lat",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
                (
                    "lng",
                    models.DecimalField(decimal_places=8, max_digits=10, null=True),
                ),
            ],
            options={
                "verbose_name": "Местоположение",
                "verbose_name_plural": "Местоположения",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Пользователь"),
                            ("admin", "Администратор"),
                            ("moderator", "Модератор"),
                        ],
                        default="member",
                        max_length=13,
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("location", models.ManyToManyField(to="users.location")),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
