# Generated by Django 4.1.1 on 2022-10-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_location_user_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="location",
            new_name="locations",
        ),
    ]
