# Generated by Django 4.1.1 on 2022-10-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_location_user_locations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="locations",
            new_name="location_id",
        ),
    ]
