# Generated by Django 4.1.1 on 2022-10-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_rename_locations_user_location_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="location_id",
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.ManyToManyField(
                null=True, related_name="loc", to="users.location"
            ),
        ),
    ]
