# Generated by Django 4.1.1 on 2022-10-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_options_remove_user_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="lat",
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="lng",
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Пользователь"),
                    ("admin", "Администратор"),
                    ("moderator", "Модератор"),
                ],
                default="member",
                max_length=13,
            ),
        ),
    ]
