# Generated by Django 4.1.1 on 2022-10-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_alter_ad_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
