# Generated by Django 4.1.1 on 2022-10-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_alter_ad_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ad",
            old_name="category",
            new_name="category_id",
        ),
    ]
