# Generated by Django 4.1.1 on 2022-10-08 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0005_rename_category_ad_category_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ad",
            old_name="author",
            new_name="author_id",
        ),
    ]
