POST http://localhost:8000/cat/create/
Content-Type: application/json

{
    "name": "Котики"
}

###

GET http://localhost:8000/cat/
Accept: application/json

###

GET http://localhost:8000/cat/1/
Accept: application/json

###

DELETE http://localhost:8000/cat/1/delete/
Accept: application/json

###

PATCH http://localhost:8000/cat/1/update/
Accept: application/json
Content-Type: application/json

{
    "name": "Неопределенно"
}

###