POST http://localhost:8000/location/
Content-Type: application/json

{
    "name": "Санкт-Петербург, ул. Гжатская, 21"
}

###

GET http://localhost:8000/location/
Accept: application/json

###

GET http://localhost:8000/location/1/
Accept: application/json

###

DELETE http://localhost:8000/location/1/
Accept: application/json

###

PATCH http://localhost:8000/location/1/
Accept: application/json
Content-Type: application/json

{
    "name": "Неопределенно"
}

###