POST http://localhost:8000/user/create/
Content-Type: application/json

{
    "first_name": "Сергей",
    "last_name": "Котенков",
    "username": "skotenkov",
    "password": "Qwer1234",
    "role": "moderator",
    "age": 26,
    "location": [
        {
            "name": "Москва, м. Студенческая",
            "lat": 55.738472,
            "lng": 37.548188
        }
    ]
}

###

GET http://localhost:8000/user/
Accept: application/json

###

POST http://localhost:8000/user/create/
Content-Type: application/json
{
    "username": "skotenkov",
    "password": "Qwer1234"
}
###

GET http://localhost:8000/user/1/
Authorization: Bearer ...

Accept: application/json

###

DELETE http://localhost:8000/user/3/delete/
Accept: application/json

###

PATCH http://localhost:8000/user/1/update/
Accept: application/json
Content-Type: application/json

{
    "first_name": "Неопределенно",
    "last_name": "Неопределенно",
    "username": "boby",
    "password": "Qwer123",
    "role": "member",
    "age": 21,
    "location": [
        {
            "name": "Новосибирск, м. Студенческая",
            "lat": 57.738472,
            "lng": 7.548188
        }
]
}


###